### ISSUE TITLE
Opaque border around popup window

### ISSUE THREAD

**Issue by rudrab** [vinceliuice/Graphite-gtk-theme#105]
when a pop up window is drawing over another window, I am getting a black shadow
![Screenshot from 2023-05-02 22-45-46](https://user-images.githubusercontent.com/4639447/235741761-5ba74bff-9b3b-4340-bff7-74cf2f8c75f3.png)

**Comment by vinceliuice** [comment]
https://gitlab.gnome.org/GNOME/mutter/-/issues/2725

**Comment by vinceliuice** [comment]
Since 44 the Non-csd windows is rendered using gtk4 with the cairo backend and cairo uses XRender on X11 surfaces - which is what glamor tries to accelerate. I would suggest to try disabling glamor by putting `XWAYLAND_NO_GLAMOR=1` in `~/.config/environment.d/00-no-glamor.conf` and then restarting your session.

**Comment by netzgestaltung** [comment]
i can confirm that same issue with the fluent theme in Fedora 38 X11 Gnome 44 Session

**Comment by rudrab** [comment]
> Since 44 the Non-csd windows is rendered using gtk4 with the cairo backend and cairo uses XRender on X11 surfaces - which is what glamor tries to accelerate. I would suggest to try disabling glamor by putting `XWAYLAND_NO_GLAMOR=1` in `~/.config/environment.d/00-no-glamor.conf` and then restarting your session.

Thanks. It has solved the problem.
