### ISSUE TITLE
dash to dock issue

### ISSUE THREAD

**Issue by starsareintherose** [vinceliuice/Graphite-gtk-theme#41]
![2022-02-05 00-22-34 的屏幕截图](https://user-images.githubusercontent.com/37733075/152620176-705077f5-c279-4ccb-b48f-7f2735af7b5c.png)
Seems like the rounded corners are influenced by the theme

**Comment by thoriqadillah** [comment]
@starsareintherose i think it's because you are using blur my shell. I was having the same issue, and then went to dash to dock github issue and found out that it was because blur my shell that caused rounder corner not working in dash to dock. The workaround is pretty simple, just disable the dash option in blur my shell extension menu

**Comment by starsareintherose** [comment]
Thanks
